export const azkarCategories = [
  {
    id: 1,
    name: "اذكار الصباح",
    value: "morning",
    description: "اذكار الصباح",
    imageUrl: "/azkar/azkar-sabah.jpg",
  },
  {
    id: 2,
    name: "اذكار المساء",
    value: "evening",
    description: "اذكار المساء",
    imageUrl: "/azkar/azkar-masa.jpg",
  },
  {
    id: 3,
    name: "اذكار النوم",
    value: "sleep",
    description: "اذكار النوم",
    imageUrl: "/azkar/azkar-nawm.jpg",
  },
  {
    id: 5,
    name: "اذكار الاستيقاظ",
    value: "wakeup",
    description: "اذكار الاستيقاظ",
    imageUrl: "/azkar/azkar-istiqaadh.jpg",
  },
  {
    id: 6,
    name: "اذكار بعد الصلاة",
    value: "after-salah",
    description: "اذكار بعد الصلاة",
    imageUrl: "/azkar/azkar-istighfar.jpg",
  },
  {
    id: 7,
    name: "أدعية الأنبياء",
    value: "anbiya-duaa",
    description: "أدعية الأنبياء",
    imageUrl: "/azkar/azkar-roqya.jpg",
  },
  {
    id: 8,
    name: "أدعية قرآنية",
    value: "quran-duaa",
    description: "أدعية قرآنية",
    imageUrl: "/azkar/azkar-siyam.jpg",
  },
  {
    id: 9,
    name: "تسابيح",
    value: "tasabeeh",
    description: "تسابيح",
    imageUrl: "/azkar/azkar-tasbeeh.jpg",
  },
];
